### ISSUE TITLE
Option to set the hightlight color

### ISSUE THREAD

**Issue by silviomoreto** [dreadatour/Flake8Lint#47]
Is there a way to set the highlight color inside the plugin? If not, could be a good feature!

**Comment by dreadatour** [comment]
Done in new version :)

**Comment by silviomoreto** [comment]
awesome! I will try right know!

**Comment by dreadatour** [comment]
Is everything ok?

**Comment by silviomoreto** [comment]
Yep! Great job!!! \o/

**Comment by silviomoreto** [comment]
Idk if you changed something, but now, the prop `pep8_max_line_length` is not working anymore.. even if I change it to a larger number than 79, it keeps warning that line is too long

**Comment by dreadatour** [comment]
Thank you, I will try to reproduce it.

**Comment by dreadatour** [comment]
Oh, wait, I use pep8_max_line_length > 79 in one of my projects and lint works fine.
Could you, please, provide more information? Config, ST version, Python version, debug output?

**Comment by silviomoreto** [comment]
Sure!
Where is the gist with my conf file: https://gist.github.com/silviomoreto/90e1c232e65a386444df
ST version: Sublime Text 3 build 3065 win 64
Python 2.7.8
Debug: 3 of 13 errors: line too long (83 > 79 characters), Line 30, Column 82
Full debug: https://gist.github.com/silviomoreto/ef14ff1d30a454c2d04d

**Comment by dreadatour** [comment]
Thank you!
Silvio, I can't see any errors in your debug output:
```
[Flake8Lint DEBUG] lint errors found: 0
```
May be the problem is you need to restart ST to make settings works?
(Next feature I planned to add is live config reload without ST restart).

**Comment by timdiller** [comment]
Did the default color change from purple to red?

**Comment by dreadatour** [comment]
Default color depends on your color sheme. In my color scheme it was red.
Plugin used 'invalid.deprecated' theme color scope name.

Now plugin uses this colors by default:
```
"highlight_color_critical": "#981600",
"highlight_color_error": "#DA2000",
"highlight_color_warning": "#EDBA00",
```
And custom color scope name.

**Comment by timdiller** [comment]
I see.  Thanks.  I was a little surprised to start up and see a very different look all of a sudden.  (I'm cleaning up someone's legacy code...)
It's certainly an improvement...  I appreciate having this package.

**Comment by dreadatour** [comment]
Tim, thank you! I am glad to hear it :)

**Comment by silviomoreto** [comment]
@dreadatour you were right! Restarted and everything worked =] ty!

**Comment by dreadatour** [comment]
@silviomoreto thank you! I will fix this and add settings reload on change soon.
