### ISSUE TITLE
On save does not highlight, popup problems

### ISSUE THREAD

**Issue by gregerc** [dreadatour/Flake8Lint#52]
For me, with Sublime Text 3 on Mac, when Flake8Lint is run on save, the highlights don't show, gutter marks don't show and selecting an error or warning in the pop-up doesn't move the cursor to that line. Using the keyboard short-cut works as expected.

**Comment by dreadatour** [comment]
Sorry for a long answer.
I've installed Origami plugin and everything works fine for me. May be Origami developers fixes the issue, or one of my previous commit fixes it. If problem is still actual, could you, please, show me your Origami views layout?
