### ISSUE TITLE
Is it possible to show the popup using a keyboard shortcut?

### ISSUE THREAD

**Issue by fgimian** [dreadatour/Flake8Lint#55]
Hey there Vladimir, love your ST plugin! :smile: 

When setting popup to false in the plugin settings, is there any way to display it using a keyboard shortcut?  Similarly, even when popup is set to true and you hide the popup, is there a way to get it back?

Forgive me if this is a silly question, but I can't seem to figure it out :smile: 

Cheers
Fotis

**Comment by dreadatour** [comment]
Sorry for a long answer. I want to add this functionality, but then I realize, that you could use "Lint" shortcut to show popup again after repeated lint :)

Simply press:

* OS X: <kbd>Ctrl+Super+8</kbd>
* Linux: <kbd>Ctrl+Alt+8</kbd>
* Windows: <kbd>Ctrl+Alt+Shift+8</kbd>

and plugin will lint your file again (in few milliseconds) and show you a popup window.

Sorry, but I really don't think this good idea to make code more heavy and complex when you could use exist functionality :)
