### ISSUE TITLE
FR: Optional real-time operation (In a separate thread)

### ISSUE THREAD

**Issue by fgimian** [dreadatour/Flake8Lint#56]
Hello again,

Have you considered the possibility of running flake8 each time code is changed in real-time?  If this was run in a separate thread and was made optional, it would be great to have so that errors would be instantly visible without having to save or run flake8 with a keyboard shortcut.

Cheers
Fotis

**Comment by dreadatour** [comment]
This feature is done in separate branch: https://github.com/dreadatour/Flake8Lint/tree/refactoring
Works only in ST3. It would be great, if you will check this before I will merge it into release branch.
