### ISSUE TITLE
setup.cfg is ignored it still lints excluded files

### ISSUE THREAD

**Issue by schmitch** [dreadatour/Flake8Lint#58]
Currently I have a project with exclude= in the setup.cfg but these line getting ignored even turning on the settings for the setup.cfg.

**Comment by dreadatour** [comment]
Hi!
Could you, please, turn on "debug" option in plugin settings and provide an output?
ST restart may be needed.

**Comment by dreadatour** [comment]
Everything works for me. Could you, please, provide more information about your config files?
