### ISSUE TITLE
No errors after changing python_interpreter

### ISSUE THREAD

**Issue by anqxyr** [dreadatour/Flake8Lint#59]
I've been getting a syntax error for "yield from", which is understandable, seeing how my default python interpreter is 2.7. To get rid of the error, I changed "python_interpreter" in Flake8Lint settings, from "auto" to "/usr/bin/python3.4".

Now most error are simply ignored. One of the few that still showup is "unexpected indent" error. But for the most part, I can write horrible code with incorrect syntax, and it won't even show me a warning.

If I change "python_interpreter" to "/usr/bin/python" instead, everything works fine as expected.

**Comment by dreadatour** [comment]
Hi! Sorry for a long answer. Could you, please, check new version? Is problem still exist?

**Comment by anqxyr** [comment]
Works great for me now. Thanks.

**Comment by stinos** [comment]
Yes, all fine now. Thanks!
