### ISSUE TITLE
Syntax Error on print statement

### ISSUE THREAD

**Issue by stranac** [dreadatour/Flake8Lint#66]
Getting syntax errors on using the print statement when running ST2 on Windows 7, with python_interpreter set to `"C:\\Python27\\pythonw.exe"`
The code is symply:

    print 'test'

If writing the print as a function, the error is gone.
From the debug output, it looks like the correct interpreter should have been used, so I can't really tell where the problem is:

    [Flake8Lint DEBUG] run lint by 'on_post_save' hook
    [Flake8Lint DEBUG] run flake8 lint
    [Flake8Lint DEBUG] ignore file patterns: []
    [Flake8Lint DEBUG] python interpreter: C:\Python27\pythonw.exe
    [Flake8Lint DEBUG] interpreter is external
    [Flake8Lint DEBUG] linter file: C:\Users\Ivan\AppData\Roaming\Sublime Text 2\Packages\Python Flake8 Lint\lint.py
    [Flake8Lint DEBUG] interpreter is external
    [Flake8Lint DEBUG] lint errors found: 1
    [Flake8Lint DEBUG] show flake8 lint errors
    [Flake8Lint DEBUG] 'select' setting: []
    [Flake8Lint DEBUG] 'ignore' setting: [u'E501', u'E261']
    [Flake8Lint DEBUG] 'is_highlight' setting: True
    [Flake8Lint DEBUG] 'is_popup' setting: True
    [Flake8Lint DEBUG] error to show: (1, 12, u'E901 SyntaxError: invalid syntax')
    [Flake8Lint DEBUG] highlight errors in view (regions: error)
    [Flake8Lint DEBUG] show popup window with errors

**Comment by dreadatour** [comment]
Thank you for bug report, i will try to reproduce it.

**Comment by zsero** [comment]
Exactly the same issue, on OS X 10.9, Sublime 2, Python 2. It is a bug in the latest release. flake8 from command line is fine, only the plugin is effected.

**Comment by dreadatour** [comment]
I think I know the reason. Fix will coming soon, thank you!

**Comment by zsero** [comment]
It's because of --naming

**Comment by dreadatour** [comment]
Not exactly. I think it's because of 'compile' function called inside lint.py where print_function is imported. I will check it out in a few hours.

**Comment by zsero** [comment]
I don't know the reason, I just know that --pep8 is OK, --pyflakes is ok, but --naming gives E901

**Comment by dreadatour** [comment]
You're right. Thank you.

**Comment by stranac** [comment]
Both of you guys seem to be right.
The code that processes `naming` seems to involve some ast generation, and future statements are inherited from the file. Simply not inheriting the future statements (using the `dont_inherit` parameter) seems to fix it.

**Comment by dreadatour** [comment]
@stranac yes, that's what I am talking about :) Thank you!

Fix with few improvements was added to master branch.
Could you, please, check it before I release it?

**Comment by zsero** [comment]
Works for me!

**Comment by dreadatour** [comment]
@stranac your fix is great, but I am also speedup lint with reduce file reads and compiles.

**Comment by stranac** [comment]
From what I see, `compile()` doesn't expect a list of lines, but a string, so it always raises a `TypeError`, so `compile_file()` returns `None`, causing both the complexity and naming checks to be skipped.

**Comment by dreadatour** [comment]
Haste makes waste. Thank you! I will double check it later before release.
