### ISSUE TITLE
Type error on running checks

### ISSUE THREAD

**Issue by lweberk** [dreadatour/Flake8Lint#68]
Hi the plugin is throwing the following error (Debug mode) on save (check on save: on).

Flake8Lint DEBUG] run lint by 'on_post_save' hook
[Flake8Lint DEBUG] run flake8 lint
[Flake8Lint DEBUG] ignore file patterns: []
[Flake8Lint DEBUG] python interpreter: /usr/bin/python3
[Flake8Lint DEBUG] interpreter is external
[Flake8Lint DEBUG] linter file: /home/xxxxxxx/.config/sublime-text-3/Packages/Python Flake8 Lint/lint.py
[Flake8Lint DEBUG] interpreter is external
[Flake8Lint DEBUG] lint time: 0.000ms
Traceback (most recent call last):
  File "/home/xxxxxxx/.config/sublime-text-3/Packages/Python Flake8 Lint/Flake8Lint.py", line 1166, in <lambda>
    lambda: Flake8Lint.async_lint(view, view_settings, quiet=quiet), 0
  File "/home/xxxxxxx/.config/sublime-text-3/Packages/Python Flake8 Lint/Flake8Lint.py", line 1229, in async_lint
    log("lint errors found: {0}".format(len(errors_list)))
TypeError: object of type 'NoneType' has no len()

Best regards
and thank you a lot for the great Plugin,
~lweberk

**Comment by dreadatour** [comment]
Oh, my bad. I will fix it right now. Thank you!

**Comment by lweberk** [comment]
Thanks!

**Comment by dreadatour** [comment]
I feel ashamed of this stupid error :)
Fixed. Could you, please, check it?

**Comment by lweberk** [comment]
Works like a charm, thanks a lot!

**Comment by dreadatour** [comment]
You're welcome! And thank you for bug report. It is very important for me :)
