### ISSUE TITLE
Restarting Sublime erases my entire Preferences.sublime-settings file!!

### ISSUE THREAD

**Issue by adams-sarah** [dreadatour/Flake8Lint#72]
I recently installed Flake8Lint for Sublime text 2 (OS X 10.10.2). The first time I restarted Sublime after installing Flake8Lint, my entire sublime settings file was wiped and replaced with:

```js
{
	"color_scheme": "Packages/User/Monokai (Flake8Lint).tmTheme",
	"font_size": 14.0
}
```

I like my custom theme, I don't want yours. Additionally, I have a bunch of other customizations that were wiped from my settings file. Meh.

I initially thought this settings-rewrite was just an on-install action. So I pieced back together my sublime settings and (stupidly) did not back it up (again).

Well I just started up Sublime this morning, only to find that my settings file had been completely wiped again. :sob: 

I would submit a pull request, but I don't know how you want to fix this.
Maybe a flag somewhere for those of us who don't want your theme?
Or at least don't re-write the entire file, check to see if the user already has a theme?

Thanks for your help,
Sarah

**Comment by dreadatour** [comment]
Hi!

Sorry for that :( I am tested this feature very carefully, and it works fine.

Flake8Lint take your theme, adds few settings in it and write new theme file near old one, so your theme is not deleted. Please, check original theme file and correct me, if I am wrong.

Settings file modified by plugin and saved by Sublime Text itself, so I am really surprised with wiped settings. My apologise again.

If you still want to help me to solve this problem, could you, please, provide me your settings file, your theme and list of installed ST plugins? You could add them here (or in gist) or send them to me by email (dreadatour@gmail.com).
