### ISSUE TITLE
Gutter and statusbar keep showing ignored errors

### ISSUE THREAD

**Issue by dukebody** [dreadatour/Flake8Lint#73]
I have set Flake8Lint to ignore the line too long errors:

    {
	"ignore": ["E501"],
    }

They correctly don't show up in the errors/warnings popup when I save. However they are highlighted in yellow in the file and have the gutter mark, and if I select the line I see in the status bar a message like "Line too long (105 > 79 characters)".

I'd expect the ignores to apply to the gutter/highlighting and status bar as well.

**Comment by grtfou** [comment]
It's work on my windows system (win 7 and win 8).
But it doesn't work on my MacBook.

**Comment by dreadatour** [comment]
Can't reproduce this bug. Does problem still exist?
