### ISSUE TITLE
__init__ for metaclasses

### ISSUE THREAD

**Issue by csira** [dreadatour/Flake8Lint#79]
N805 popping up for __init__ methods in metaclasses, whose first argument is generally "cls".

![screen shot 2015-10-06 at 7 15 18 am](https://cloud.githubusercontent.com/assets/916189/10307129/23f75b14-6bfa-11e5-801f-48c0317c634d.png)

Thanks for taking a look!

**Comment by dreadatour** [comment]
It seems there is a bug in pep8-naming and author did not want to fix it. See this Issue: https://github.com/PyCQA/pep8-naming/issues/3 in pep8-naming repository.

You could add this error (N805) to ignore list (I prefer this way) or add a "noqa" comment to this line (but this is not good practice).
